### ISSUE TITLE
mobs invisable bug

### ISSUE THREAD

**Issue by GothkittyGirl** [BillyGalbreath/Ridables#1]
[04:19:59] [Server thread/INFO]: [Ridables] Loading Ridables v2.5
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mchicken[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mcow[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected new entity: [32mdolphin_spit[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mdolphin[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mDragon disabled. Skipping..[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mllama[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mmooshroom[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mocelot[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mphantom[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mpolar_bear[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [31mCould not inject new ridable entity to registry! Restart your server to try again! ([33msheep[31m)[0m
[04:20:00] [Server thread/WARN]: java.lang.ArrayIndexOutOfBoundsException: -1
[04:20:00] [Server thread/WARN]: 	at net.pl3x.bukkit.ridables.util.RegistryHax.injectReplacementEntityTypes(RegistryHax.java:70)
[04:20:00] [Server thread/WARN]: 	at net.pl3x.bukkit.ridables.Ridables.onLoad(Ridables.java:176)
[04:20:00] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_13_R1.CraftServer.loadPlugins(CraftServer.java:319)
[04:20:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.DedicatedServer.init(DedicatedServer.java:213)
[04:20:00] [Server thread/WARN]: 	at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:686)
[04:20:00] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:748)
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mturtle[0m
[04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [33mSuccessfully injected replacement entity: [32mwolf[0m

any mob having the issued error: [04:20:00] [Server thread/INFO]: [33m[[36mRidables[33m][0m [31mCould not inject new ridable entity to registry! Restart your server to try again! ([33msheep[31m)[0m

will not load in but sounds and action till happen

**Comment by BillyGalbreath** [comment]
Did you read what the message said? When you see that you need to restart the server because the injection failed.

`[04:20:00] [Server thread/INFO]: [Ridables] Could not inject new ridable entity to registry! Restart your server to try again! (sheep)`

**Comment by BillyGalbreath** [comment]
Try v2.6 to see if it makes those errors happen less often.

**Comment by GothkittyGirl** [comment]
fixed the loading up but disabled mobs turn invis

**Comment by BillyGalbreath** [comment]
Ok, try v2.6.1

**Comment by GothkittyGirl** [comment]
some what fixed but with v2.7.3 ocelots are invis til a second restart. easy fix i think but just thought you should know and about to update to newest version
