### ISSUE TITLE
Incompatibility with Citizens - Turtle

### ISSUE THREAD

**Issue by relucaXIV** [BillyGalbreath/Ridables#29]
If I enable Turtles Ridable when I restart Turtles NPC will not load giving me this error in console:
`[19:52:08 WARN]: java.lang.IllegalArgumentException: unable to find valid entity superclass for class class net.citizensnpcs.nms.v1_13_R2.entity.TurtleController$EntityTurtleNPC
[19:52:08 WARN]:        at net.citizensnpcs.nms.v1_13_R2.util.NMSImpl.registerEntityClass(NMSImpl.java:748)
[19:52:08 WARN]:        at net.citizensnpcs.util.NMS.registerEntityClass(NMS.java:222)
[19:52:08 WARN]:        at net.citizensnpcs.npc.AbstractEntityController.<init>(AbstractEntityController.java:16)
[19:52:08 WARN]:        at net.citizensnpcs.nms.v1_13_R2.entity.MobEntityController.<init>(MobEntityController.java:21)
[19:52:08 WARN]:        at net.citizensnpcs.nms.v1_13_R2.entity.TurtleController.<init>(TurtleController.java:21)
[19:52:08 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[19:52:08 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[19:52:08 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[19:52:08 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[19:52:08 WARN]:        at java.lang.Class.newInstance(Class.java:442)
[19:52:08 WARN]:        at net.citizensnpcs.npc.EntityControllers.createForType(EntityControllers.java:20)
[19:52:08 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:103)
[19:52:08 WARN]:        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:50)
[19:52:08 WARN]:        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56)
[19:52:08 WARN]:        at net.citizensnpcs.Citizens$2.run(Citizens.java:306)
[19:52:08 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63)
[19:52:08 WARN]:        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423)
[19:52:08 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008)
[19:52:08 WARN]:        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439)
[19:52:08 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943)
[19:52:08 WARN]:        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841)
[19:52:08 WARN]:        at java.lang.Thread.run(Thread.java:748)
[19:52:08 WARN]: [Citizens] Task #134 for Citizens v2.0.24-SNAPSHOT (build 1605) generated an exception
java.lang.NullPointerException: null
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:770) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at net.citizensnpcs.npc.CitizensNPC.<init>(CitizensNPC.java:56) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPCRegistry.getByType(CitizensNPCRegistry.java:103) ~[?:?]
        at net.citizensnpcs.npc.CitizensNPCRegistry.createNPC(CitizensNPCRegistry.java:50) ~[?:?]
        at net.citizensnpcs.api.npc.SimpleNPCDataStore.loadInto(SimpleNPCDataStore.java:56) ~[?:?]
        at net.citizensnpcs.Citizens$2.run(Citizens.java:306) ~[?:?]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftTask.run(CraftTask.java:63) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at org.bukkit.craftbukkit.v1_13_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:423) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at net.minecraft.server.v1_13_R2.MinecraftServer.b(MinecraftServer.java:1008) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at net.minecraft.server.v1_13_R2.DedicatedServer.b(DedicatedServer.java:439) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at net.minecraft.server.v1_13_R2.MinecraftServer.a(MinecraftServer.java:943) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at net.minecraft.server.v1_13_R2.MinecraftServer.run(MinecraftServer.java:841) ~[PaperSpigot-1.13.2.jar:git-Paper-454]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]`

**Comment by BillyGalbreath** [comment]
This is a known compatibility issue, and it cannot be resolved.

You can only have 1 custom vanilla entity. Either disable turtles in Citizens, or disable it in Ridables. This is why things like this have configuration options. ;)
